---
title: "chp3"
author: "Vasco Brazão"
date: "12/5/2020"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages
```{r packages}
library(tidyverse)
library(rethinking)
```

Code for the easy problems (from book):

```{r easy.samples}

p_grid <- seq( from=0 , to=1 , length.out=1000 )
prior <- rep( 1 , 1000 )
likelihood <- dbinom( 6 , size=9 , prob=p_grid )
posterior <- likelihood * prior
posterior <- posterior / sum(posterior)

set.seed(100)

samples <- sample(p_grid, prob = posterior, size = 1e4, replace = TRUE)
```

## 3E1

```{r 3e1}
sum(samples < .2) / length(samples)
```
## 3E2

```{r 3e2}
sum(samples > .8) / length(samples)
```
## 3E3

```{r 3e3}
(sum(samples > .2) - sum(samples >= .8))/ length(samples)
```
## 3E4

```{r 3e4}
quantile(samples, .2)
```
## 3E5

```{r 3e5}
quantile(samples, .8)
```
## 3E6

```{r 3e6}
rethinking::HPDI(samples, .66)
```

## 3E7

```{r 3e7}
rethinking::PI(samples, .66)
```
## 3M1
This time trying to be a little more tidyverse-y
```{r 3m1}
globe <- tibble(
  p_grid = seq(from = 0, to = 1, length.out = 1000),
  prior = rep(1, 1000),
  likelihood = dbinom(8, size = 15, prob = p_grid),
  posterior = likelihood * prior / sum(likelihood * prior)
)

#a graph for good measure

globe3m1post <- globe %>%
  ggplot(aes(x = p_grid, y = posterior)) +
  geom_line()

print(globe3m1post)
```

## 3M2

```{r 3m2}
set.seed(100)

samples <- sample(globe$p_grid, prob = globe$posterior, size = 1e4, replace = TRUE)

rethinking::HPDI(samples, .90)
```

## 3M3

```{r 3m3}
w <- rbinom(1e4, size = 15, prob=samples)

# probability of 8 W
sum(w == 8)/1e4
```
